# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosProducto',
            fields=[
                ('id_Producto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
